# Site settings
title:       Jekyllized Story
description: "A simple tale made complicated."  # Used in index.html but also for SEO in _includes/_head.html
baseurl:     "/jekyllized-story"                # the subpath of your site, e.g. /blog
url:         ""                                 # the base hostname & protocol for your site
date_format: "%b %-d, %Y"                       # see _layouts/post.html
footer_note: '&copy; Creative Directions. Theme by <a href="https://html5up.net">HTML5 UP</a>.'
demo_script: true                             # this loads the assets/js/demo.js for index.html

# SEO
admin:      "Creative Directions"
admin_city: "Hong Kong"                         # used for SEO, see _includes/head.html
admin_state: "Hong Kong"                        # used for SEO, see _includes/head.html
share-image: "/images/share.png"                # used for SEO, see _includes/_head.html

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /blog/:slug
sass:
  sass_dir: assets/_sass
  style: compressed
plugins:
  - jekyll-sitemap
#  - jemoji

# https://github.com/jekyll/jekyll/issues/2938
exclude: ["Gemfile", "Gemfile.lock", node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/","docker-compose.yml","story_jekyll_theme.gemspec"]
